<?php
declare(strict_types=1);

require __DIR__ . '/app/bootstrap.php';

use App\Core\Router;
use App\Controllers\PublicController;
use App\Controllers\AuthController;
use App\Controllers\WriterController;
use App\Controllers\AdminController;
use App\Controllers\AdminToolsController;
use App\Controllers\AdController;
use App\Controllers\CommunityController;
use App\Controllers\AdminCommunityController;
use App\Controllers\AdminCommentsController;
use App\Controllers\EditorialMessagesController;
use App\Controllers\KhawatirController;
use App\Controllers\WriterCardController;

$router = new Router();
$defaultLocale = default_locale();

$router->get('/', [PublicController::class, 'root']);
$router->get('/behind-saradeeb', fn() => (new PublicController())->behindSaradeeb($defaultLocale));
$router->get('/sitemap.xml', [PublicController::class, 'sitemap']);
$router->get('/robots.txt', [PublicController::class, 'robots']);
$router->get('/llms.txt', [PublicController::class, 'llms']);
$router->get('/llms-full.txt', [PublicController::class, 'llmsFull']);
$router->get('/feed.xml', [PublicController::class, 'feed']);

$router->post('/logout', [AuthController::class, 'logout']);
$router->post('/impersonation/stop', [AuthController::class, 'stopImpersonation']);
$router->get('/two-factor', [AuthController::class, 'twoFactorForm']);
$router->post('/two-factor', [AuthController::class, 'twoFactor']);
$router->get('/ad/click/{id}', [AdController::class, 'click']);

$router->get('/writer', [WriterController::class, 'dashboard']);
$router->get('/writer/articles/new', [WriterController::class, 'edit']);
$router->get('/writer/articles/{id}', [WriterController::class, 'edit']);
$router->get('/writer/articles/{id}/preview/{locale}', [WriterController::class, 'preview']);
$router->post('/writer/articles/save', [WriterController::class, 'save']);
$router->post('/writer/articles/submit', [WriterController::class, 'submit']);
$router->get('/writer/account', [WriterController::class, 'account']);
$router->post('/writer/account/profile', [WriterController::class, 'saveProfile']);
$router->get('/writer/username/check', [WriterController::class, 'checkUsername']);
$router->post('/writer/account/password', [WriterController::class, 'changePassword']);
$router->post('/writer/notifications/read', [WriterController::class, 'readNotification']);
$router->get('/writer/share-center', [WriterController::class, 'shareCenter']);
$router->get('/writer/card', [WriterCardController::class, 'index']);
$router->post('/writer/card/save', [WriterCardController::class, 'save']);
$router->post('/writer/account/avatar', [WriterController::class, 'uploadAvatar']);
$router->get('/writer/editorial-messages', [EditorialMessagesController::class, 'index']);
$router->post('/writer/editorial-messages/start', [EditorialMessagesController::class, 'writerStart']);
$router->post('/writer/editorial-messages/send', [EditorialMessagesController::class, 'send']);
$router->get('/writer/khawatir', [KhawatirController::class, 'writerIndex']);
$router->get('/writer/khawatir/new', [KhawatirController::class, 'edit']);
$router->get('/writer/khawatir/{id}', [KhawatirController::class, 'edit']);
$router->post('/writer/khawatir/save', [KhawatirController::class, 'save']);
$router->post('/writer/khawatir/submit', [KhawatirController::class, 'submit']);
$router->post('/writer/khawatir/delete', [KhawatirController::class, 'delete']);

$router->get('/admin', [AdminController::class, 'dashboard']);
$router->get('/admin-app', [AdminController::class, 'mobileApp']);
$router->get('/admin/articles', [AdminController::class, 'articles']);
$router->get('/admin/articles/{id}', [AdminController::class, 'editArticle']);
$router->post('/admin/articles/review', [AdminController::class, 'reviewArticle']);
$router->get('/admin/podcast', [AdminController::class, 'podcast']);
$router->get('/admin/podcast/new', [AdminController::class, 'editPodcast']);
$router->get('/admin/podcast/{id}', [AdminController::class, 'editPodcast']);
$router->post('/admin/podcast/save', [AdminController::class, 'savePodcast']);
$router->post('/admin/podcast/delete', [AdminController::class, 'deletePodcast']);
$router->get('/admin/khawatir', [KhawatirController::class, 'adminIndex']);
$router->get('/admin/khawatir/{id}', [KhawatirController::class, 'adminEdit']);
$router->post('/admin/khawatir/review', [KhawatirController::class, 'review']);
$router->post('/admin/khawatir/category/save', [KhawatirController::class, 'saveCategory']);
$router->post('/admin/khawatir/settings', [KhawatirController::class, 'saveSettings']);
$router->get('/admin/writer-cards', [WriterCardController::class, 'admin']);
$router->post('/admin/writer-cards/save', [WriterCardController::class, 'adminSave']);
$router->get('/admin/comments', [AdminCommentsController::class, 'index']);
$router->get('/admin/editorial-messages', [EditorialMessagesController::class, 'index']);
$router->post('/admin/editorial-messages/create', [EditorialMessagesController::class, 'create']);
$router->post('/admin/editorial-messages/send', [EditorialMessagesController::class, 'send']);
$router->post('/admin/editorial-messages/archive', [EditorialMessagesController::class, 'archive']);
$router->post('/admin/comments/action', [AdminCommentsController::class, 'action']);
$router->post('/admin/comments/delete', [AdminCommentsController::class, 'delete']);
$router->post('/admin/comments/settings', [AdminCommentsController::class, 'settings']);

$router->get('/admin/pages', [AdminController::class, 'pages']);
$router->get('/admin/pages/new', [AdminController::class, 'editPage']);
$router->get('/admin/pages/{id}', [AdminController::class, 'editPage']);
$router->post('/admin/pages/save', [AdminController::class, 'savePage']);
$router->post('/admin/pages/toggle', [AdminController::class, 'togglePage']);
$router->post('/admin/pages/footer', [AdminController::class, 'togglePageFooter']);
$router->post('/admin/pages/trash', [AdminController::class, 'trashPage']);
$router->post('/admin/pages/restore', [AdminController::class, 'restorePage']);

$router->get('/admin/users', [AdminController::class, 'users']);
$router->post('/admin/users/save', [AdminController::class, 'saveUser']);
$router->get('/admin/writers', [AdminController::class, 'writers']);
$router->get('/admin/writers/{id}', [AdminController::class, 'writerDetail']);
$router->post('/admin/writers/save', [AdminController::class, 'saveWriter']);
$router->post('/admin/users/impersonate', [AdminController::class, 'impersonateWriter']);
$router->get('/admin/writer-applications', [AdminController::class, 'writerApplications']);
$router->post('/admin/writer-applications/update', [AdminController::class, 'updateWriterApplication']);
$router->post('/admin/writer-applications/create-user', [AdminController::class, 'createWriterFromApplication']);

$router->get('/admin/categories', [AdminController::class, 'categories']);
$router->post('/admin/categories/save', [AdminController::class, 'saveCategory']);
$router->post('/admin/tags/save', [AdminController::class, 'saveTag']);

$router->get('/admin/ads', [AdminController::class, 'ads']);
$router->post('/admin/ads/save', [AdminController::class, 'saveAd']);
$router->post('/admin/ads/toggle', [AdminController::class, 'toggleAd']);
$router->post('/admin/ads/delete', [AdminController::class, 'deleteAd']);


$router->get('/admin/notes', [AdminController::class, 'notes']);
$router->post('/admin/notes/save', [AdminController::class, 'saveNote']);
$router->post('/admin/notes/delete', [AdminController::class, 'deleteNote']);
$router->get('/admin/activity', [AdminController::class, 'activity']);
$router->get('/admin/thanks', [AdminController::class, 'thanks']);
$router->post('/admin/thanks/save', [AdminController::class, 'saveThanks']);
$router->get('/admin/site-notifications', [AdminController::class, 'siteNotifications']);
$router->post('/admin/site-notifications/save', [AdminController::class, 'saveSiteNotification']);
$router->post('/admin/site-notifications/delete', [AdminController::class, 'deleteSiteNotification']);
$router->get('/admin/backup', [AdminController::class, 'backup']);
$router->post('/admin/backup/download', [AdminController::class, 'downloadBackup']);
$router->get('/admin/languages', [AdminToolsController::class, 'languages']);
$router->post('/admin/languages/save', [AdminToolsController::class, 'saveLanguage']);
$router->post('/admin/languages/delete', [AdminToolsController::class, 'deleteLanguage']);
$router->post('/admin/languages/translations/save', [AdminToolsController::class, 'saveTranslations']);
$router->get('/admin/languages/export', [AdminToolsController::class, 'exportTranslations']);
$router->post('/admin/languages/import', [AdminToolsController::class, 'importTranslations']);
$router->get('/admin/languages/import/{id}', [AdminToolsController::class, 'importPreview']);
$router->post('/admin/languages/import/{id}/confirm', [AdminToolsController::class, 'confirmTranslationImport']);
$router->get('/admin/navigation', [AdminController::class, 'navigation']);
$router->post('/admin/navigation/save', [AdminController::class, 'saveNavigation']);
$router->get('/admin/story-submissions', [AdminToolsController::class, 'storySubmissions']);
$router->get('/admin/messages', [AdminToolsController::class, 'messages']);
$router->post('/admin/messages/update', [AdminToolsController::class, 'updateMessage']);
$router->post('/admin/messages/delete', [AdminToolsController::class, 'deleteMessage']);
$router->post('/admin/story-submissions/update', [AdminToolsController::class, 'updateStorySubmission']);
$router->post('/admin/story-submissions/delete', [AdminToolsController::class, 'deleteStorySubmission']);
$router->get('/admin/newsletter', [AdminToolsController::class, 'newsletter']);
$router->post('/admin/newsletter/toggle', [AdminToolsController::class, 'newsletterToggle']);
$router->post('/admin/newsletter/delete', [AdminToolsController::class, 'newsletterDelete']);
$router->get('/admin/media', [AdminToolsController::class, 'media']);
$router->post('/admin/media/upload', [AdminToolsController::class, 'uploadMedia']);
$router->post('/admin/media/upload-ajax', [AdminToolsController::class, 'uploadMediaAjax']);
$router->post('/admin/media/update', [AdminToolsController::class, 'updateMedia']);
$router->post('/admin/media/delete', [AdminToolsController::class, 'deleteMedia']);
$router->post('/admin/media/bulk-delete', [AdminToolsController::class, 'bulkDeleteMedia']);
$router->post('/admin/media/restore', [AdminToolsController::class, 'restoreMedia']);
$router->post('/admin/media/folders', [AdminToolsController::class, 'createMediaFolder']);
$router->get('/admin/blocks', [AdminToolsController::class, 'blocks']);
$router->post('/admin/blocks/save', [AdminToolsController::class, 'saveBlock']);
$router->post('/admin/blocks/delete', [AdminToolsController::class, 'deleteBlock']);
$router->post('/admin/backup/restore', [AdminToolsController::class, 'restoreBackup']);
$router->get('/admin/system', [AdminToolsController::class, 'system']);
$router->get('/admin/security', [AdminToolsController::class, 'security']);
$router->post('/admin/security/2fa/enable', [AdminToolsController::class, 'enableTwoFactor']);
$router->post('/admin/security/2fa/disable', [AdminToolsController::class, 'disableTwoFactor']);
$router->post('/admin/security/save', [AdminToolsController::class, 'saveSecurity']);
$router->get('/admin/links', [AdminToolsController::class, 'links']);
$router->post('/admin/links/redirect/save', [AdminToolsController::class, 'saveRedirect']);
$router->post('/admin/links/redirect/delete', [AdminToolsController::class, 'deleteRedirect']);
$router->post('/admin/links/404/clear', [AdminToolsController::class, 'clear404Logs']);
$router->get('/admin/articles/{id}/revisions', [AdminToolsController::class, 'revisions']);
$router->post('/admin/articles/revisions/restore', [AdminToolsController::class, 'restoreRevision']);
$router->get('/admin/settings', [AdminController::class, 'settings']);
$router->post('/admin/settings/save', [AdminController::class, 'saveSettings']);
$router->post('/admin/settings/test-mail', [AdminController::class, 'testMail']);
$router->get('/admin/appearance', [AdminController::class, 'appearance']);
$router->post('/admin/appearance/save', [AdminController::class, 'saveAppearance']);
$router->get('/admin/typography', [AdminController::class, 'typography']);
$router->post('/admin/typography/save', [AdminController::class, 'saveTypography']);
$router->get('/admin/header', [AdminController::class, 'headerEditor']);
$router->post('/admin/header/save', [AdminController::class, 'saveHeaderEditor']);
$router->get('/admin/footer', [AdminController::class, 'footerEditor']);
$router->post('/admin/footer/save', [AdminController::class, 'saveFooterEditor']);
$router->get('/admin/whatsapp', [AdminController::class, 'whatsapp']);
$router->post('/admin/whatsapp/save', [AdminController::class, 'saveWhatsapp']);
$router->get('/admin/social', [AdminController::class, 'social']);
$router->post('/admin/social/save', [AdminController::class, 'saveSocial']);
$router->get('/admin/protection', [AdminController::class, 'protection']);
$router->post('/admin/protection/save', [AdminController::class, 'saveProtection']);
$router->get('/admin/integrations', [AdminController::class, 'integrations']);
$router->post('/admin/integrations/save', [AdminController::class, 'saveIntegration']);
$router->post('/admin/integrations/consent', [AdminController::class, 'saveTrackingConsent']);
$router->post('/admin/integrations/ad-slots', [AdminController::class, 'saveAdSlots']);
$router->post('/admin/integrations/custom/save', [AdminController::class, 'saveCustomTrackingCode']);
$router->post('/admin/integrations/custom/toggle', [AdminController::class, 'toggleCustomTrackingCode']);
$router->post('/admin/integrations/custom/delete', [AdminController::class, 'deleteCustomTrackingCode']);

$router->get('/admin/community', [AdminCommunityController::class, 'index']);
$router->post('/admin/community/category/save', [AdminCommunityController::class, 'saveCategory']);
$router->post('/admin/community/category/delete', [AdminCommunityController::class, 'deleteCategory']);
$router->post('/admin/community/topic-action', [AdminCommunityController::class, 'topicAction']);
$router->post('/admin/community/reply-action', [AdminCommunityController::class, 'replyAction']);
$router->post('/admin/community/report-action', [AdminCommunityController::class, 'reportAction']);
$router->post('/admin/community/ban', [AdminCommunityController::class, 'banUser']);
$router->post('/admin/community/unban', [AdminCommunityController::class, 'unbanUser']);
$router->post('/admin/community/settings', [AdminCommunityController::class, 'saveSettings']);

$router->get('/admin/import-wordpress', [AdminController::class, 'importForm']);
$router->post('/admin/import-wordpress', [AdminController::class, 'importWordpress']);
$router->get('/admin/export-articles', [AdminController::class, 'exportArticlesForm']);
$router->post('/admin/export-articles', [AdminController::class, 'exportArticles']);

// Clean URLs for the default language: Arabic does not require /ar.
$router->get('/login', fn() => (new AuthController())->loginForm($defaultLocale));
$router->post('/login', fn() => (new AuthController())->login($defaultLocale));
$router->get('/register', fn() => (new AuthController())->registerForm($defaultLocale));
$router->post('/register', fn() => (new AuthController())->register($defaultLocale));
$router->get('/writer-application', fn() => (new AuthController())->applicationForm($defaultLocale));
$router->post('/writer-application', fn() => (new AuthController())->submitApplication($defaultLocale));
$router->get('/verify-writer-application', fn() => (new AuthController())->verifyWriterApplication($defaultLocale));
$router->get('/activate', fn() => (new AuthController())->activationForm($defaultLocale));
$router->post('/activate', fn() => (new AuthController())->activate($defaultLocale));
$router->get('/forgot-password', fn() => (new AuthController())->forgotForm($defaultLocale));
$router->post('/forgot-password', fn() => (new AuthController())->forgot($defaultLocale));
$router->get('/reset-password', fn() => (new AuthController())->resetForm($defaultLocale));
$router->post('/reset-password', fn() => (new AuthController())->reset($defaultLocale));
$router->get('/article/{slug}', fn($slug) => (new PublicController())->article($defaultLocale,$slug));
$router->post('/article/{slug}/comment', fn($slug) => (new PublicController())->submitComment($defaultLocale,$slug));
$router->get('/podcast', fn() => (new PublicController())->podcast($defaultLocale));
$router->get('/podcast/{slug}', fn($slug) => (new PublicController())->podcastEpisode($defaultLocale,$slug));
$router->get('/khawatir', fn() => (new KhawatirController())->index($defaultLocale));
$router->get('/khawatir/{slug}', fn($slug) => (new KhawatirController())->show($defaultLocale,$slug));
$router->get('/category/{slug}', fn($slug) => (new PublicController())->category($defaultLocale,$slug));
$router->get('/writer/{username}', fn($username) => (new PublicController())->author($defaultLocale,$username));
$router->get('/author/{username}', fn($username) => redirect(writer_url($username,$defaultLocale),301));
$router->get('/search', fn() => (new PublicController())->search($defaultLocale));
$router->get('/page/{slug}', fn($slug) => (new PublicController())->page($defaultLocale,$slug));
$router->get('/send-story', fn() => (new PublicController())->sendStoryForm($defaultLocale));
$router->post('/send-story', fn() => (new PublicController())->submitStory($defaultLocale));
$router->get('/contact', fn() => (new PublicController())->contactForm($defaultLocale));
$router->post('/contact', fn() => (new PublicController())->submitContact($defaultLocale));
$router->post('/newsletter/subscribe', fn() => (new PublicController())->subscribeNewsletter($defaultLocale));

$router->get('/community', fn() => (new CommunityController())->index($defaultLocale));
$router->get('/writers', fn() => (new PublicController())->writers($defaultLocale));
$router->get('/community/new', fn() => (new CommunityController())->createForm($defaultLocale));
$router->post('/community/new', fn() => (new CommunityController())->storeTopic($defaultLocale));
$router->get('/community/topic/{slug}', fn($slug) => (new CommunityController())->topic($defaultLocale,$slug));
$router->get('/community/member/{username}', fn($username) => (new CommunityController())->member($defaultLocale,$username));
$router->get('/community/article/{id}', fn($id) => (new CommunityController())->articleDiscussion($defaultLocale,$id));
$router->post('/community/reply', fn() => (new CommunityController())->storeReply($defaultLocale));
$router->post('/community/like', fn() => (new CommunityController())->toggleLike($defaultLocale));
$router->post('/community/follow', fn() => (new CommunityController())->toggleFollow($defaultLocale));
$router->post('/community/save', fn() => (new CommunityController())->toggleSave($defaultLocale));
$router->post('/community/report', fn() => (new CommunityController())->report($defaultLocale));
$router->get('/community/notifications', fn() => (new CommunityController())->notifications($defaultLocale));
$router->post('/community/notifications/read', fn() => (new CommunityController())->markNotificationsRead($defaultLocale));
$router->get('/community/saved', fn() => (new CommunityController())->saved($defaultLocale));
$router->get('/community/preferences', fn() => (new CommunityController())->preferences($defaultLocale));
$router->post('/community/preferences', fn() => (new CommunityController())->savePreferences($defaultLocale));
$router->get('/community/account', fn() => (new CommunityController())->account($defaultLocale));
$router->post('/community/account', fn() => (new CommunityController())->saveAccount($defaultLocale));
$router->get('/community/{slug}', fn($slug) => (new CommunityController())->category($defaultLocale,$slug));


// Localized URLs for optional secondary languages.
$router->get('/{locale}/login', [AuthController::class, 'loginForm']);
$router->post('/{locale}/login', [AuthController::class, 'login']);
$router->get('/{locale}/register', [AuthController::class, 'registerForm']);
$router->post('/{locale}/register', [AuthController::class, 'register']);
$router->get('/{locale}/writer-application', [AuthController::class, 'applicationForm']);
$router->post('/{locale}/writer-application', [AuthController::class, 'submitApplication']);
$router->get('/{locale}/verify-writer-application', [AuthController::class, 'verifyWriterApplication']);
$router->get('/{locale}/activate', [AuthController::class, 'activationForm']);
$router->post('/{locale}/activate', [AuthController::class, 'activate']);
$router->get('/{locale}/forgot-password', [AuthController::class, 'forgotForm']);
$router->post('/{locale}/forgot-password', [AuthController::class, 'forgot']);
$router->get('/{locale}/reset-password', [AuthController::class, 'resetForm']);
$router->post('/{locale}/reset-password', [AuthController::class, 'reset']);
$router->get('/{locale}/article/{slug}', [PublicController::class, 'article']);
$router->get('/{locale}/behind-saradeeb', [PublicController::class, 'behindSaradeeb']);
$router->post('/{locale}/article/{slug}/comment', [PublicController::class, 'submitComment']);
$router->get('/{locale}/podcast', [PublicController::class, 'podcast']);
$router->get('/{locale}/podcast/{slug}', [PublicController::class, 'podcastEpisode']);
$router->get('/{locale}/khawatir', [KhawatirController::class, 'index']);
$router->get('/{locale}/khawatir/{slug}', [KhawatirController::class, 'show']);
$router->get('/{locale}/category/{slug}', [PublicController::class, 'category']);
$router->get('/{locale}/writer/{username}', [PublicController::class, 'author']);
$router->get('/{locale}/writers', [PublicController::class, 'writers']);
$router->get('/{locale}/author/{username}', fn($locale,$username) => redirect(writer_url($username,$locale),301));
$router->get('/{locale}/search', [PublicController::class, 'search']);
$router->get('/{locale}/page/{slug}', [PublicController::class, 'page']);
$router->get('/{locale}/send-story', [PublicController::class, 'sendStoryForm']);
$router->post('/{locale}/send-story', [PublicController::class, 'submitStory']);
$router->get('/{locale}/contact', [PublicController::class, 'contactForm']);
$router->post('/{locale}/contact', [PublicController::class, 'submitContact']);
$router->post('/{locale}/newsletter/subscribe', [PublicController::class, 'subscribeNewsletter']);

$router->get('/{locale}/community', [CommunityController::class, 'index']);
$router->get('/{locale}/community/new', [CommunityController::class, 'createForm']);
$router->post('/{locale}/community/new', [CommunityController::class, 'storeTopic']);
$router->get('/{locale}/community/topic/{slug}', [CommunityController::class, 'topic']);
$router->get('/{locale}/community/member/{username}', [CommunityController::class, 'member']);
$router->get('/{locale}/community/article/{id}', [CommunityController::class, 'articleDiscussion']);
$router->post('/{locale}/community/reply', [CommunityController::class, 'storeReply']);
$router->post('/{locale}/community/like', [CommunityController::class, 'toggleLike']);
$router->post('/{locale}/community/follow', [CommunityController::class, 'toggleFollow']);
$router->post('/{locale}/community/save', [CommunityController::class, 'toggleSave']);
$router->post('/{locale}/community/report', [CommunityController::class, 'report']);
$router->get('/{locale}/community/notifications', [CommunityController::class, 'notifications']);
$router->post('/{locale}/community/notifications/read', [CommunityController::class, 'markNotificationsRead']);
$router->get('/{locale}/community/saved', [CommunityController::class, 'saved']);
$router->get('/{locale}/community/preferences', [CommunityController::class, 'preferences']);
$router->post('/{locale}/community/preferences', [CommunityController::class, 'savePreferences']);
$router->get('/{locale}/community/account', [CommunityController::class, 'account']);
$router->post('/{locale}/community/account', [CommunityController::class, 'saveAccount']);
$router->get('/{locale}/community/{slug}', [CommunityController::class, 'category']);

$router->get('/{locale}', [PublicController::class, 'home']);

$router->dispatch($_SERVER['REQUEST_METHOD'] ?? 'GET', $_SERVER['REQUEST_URI'] ?? '/');
